import type { Pokemon } from '@/types/pokemon';

const createPokemon = (id: number, name: string, types: string[], isHisuian: boolean = false): Pokemon => {
  const imageName = name.toLowerCase().replace(' ', '-').replace("'", "");
  const imageUrl = `https://img.pokemondb.net/sprites/legends-arceus/normal/${imageName}${isHisuian ? '-hisuian' : ''}.png`;
  
  // Special cases for forms
  if (name === 'Wormadam') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/wormadam-plant.png`,
      types
    };
  }
  if (name === 'Basculin') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/basculin-white-striped.png`,
      types
    };
  }
  if (name === 'Tornadus' || name === 'Thundurus' || name === 'Landorus' || name === 'Enamorus') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/${imageName}-incarnate.png`,
      types
    };
  }
  if (name === 'Dialga' || name === 'Palkia') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/${imageName}-origin.png`,
      types
    };
  }
  if (name === 'Shaymin') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/shaymin-land.png`,
      types
    };
  }
  if (name === 'Giratina') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/giratina-origin.png`,
      types
    };
  }

  return {
    id,
    name,
    imageUrl,
    types,
  };
};

export const pokemonList: Pokemon[] = [
  createPokemon(1, 'Rowlet', ['Grass', 'Flying']),
  createPokemon(2, 'Dartrix', ['Grass', 'Flying']),
  createPokemon(3, 'Decidueye', ['Grass', 'Fighting'], true),
  createPokemon(4, 'Cyndaquil', ['Fire']),
  createPokemon(5, 'Quilava', ['Fire']),
  createPokemon(6, 'Typhlosion', ['Fire', 'Ghost'], true),
  createPokemon(7, 'Oshawott', ['Water']),
  createPokemon(8, 'Dewott', ['Water']),
  createPokemon(9, 'Samurott', ['Water', 'Dark'], true),
  createPokemon(10, 'Bidoof', ['Normal']),
  createPokemon(11, 'Bibarel', ['Normal', 'Water']),
  createPokemon(12, 'Starly', ['Normal', 'Flying']),
  createPokemon(13, 'Staravia', ['Normal', 'Flying']),
  createPokemon(14, 'Staraptor', ['Normal', 'Flying']),
  createPokemon(15, 'Shinx', ['Electric']),
  createPokemon(16, 'Luxio', ['Electric']),
  createPokemon(17, 'Luxray', ['Electric']),
  createPokemon(18, 'Wurmple', ['Bug', 'Poison']),
  createPokemon(19, 'Silcoon', ['Bug']),
  createPokemon(20, 'Beautifly', ['Bug', 'Flying']),
  createPokemon(21, 'Cascoon', ['Bug']),
  createPokemon(22, 'Dustox', ['Bug', 'Poison']),
  createPokemon(23, 'Ponyta', ['Fire']),
  createPokemon(24, 'Rapidash', ['Fire']),
  createPokemon(25, 'Eevee', ['Normal']),
  createPokemon(26, 'Vaporeon', ['Water']),
  createPokemon(27, 'Jolteon', ['Electric']),
  createPokemon(28, 'Flareon', ['Fire']),
  createPokemon(29, 'Espeon', ['Psychic']),
  createPokemon(30, 'Umbreon', ['Dark']),
  createPokemon(31, 'Leafeon', ['Grass']),
  createPokemon(32, 'Glaceon', ['Ice']),
  createPokemon(33, 'Sylveon', ['Fairy']),
  createPokemon(34, 'Zubat', ['Poison', 'Flying']),
  createPokemon(35, 'Golbat', ['Poison', 'Flying']),
  createPokemon(36, 'Crobat', ['Poison', 'Flying']),
  createPokemon(37, 'Drifloon', ['Ghost', 'Flying']),
  createPokemon(38, 'Drifblim', ['Ghost', 'Flying']),
  createPokemon(39, 'Kricketot', ['Bug']),
  createPokemon(40, 'Kricketune', ['Bug']),
  createPokemon(41, 'Buizel', ['Water']),
  createPokemon(42, 'Floatzel', ['Water']),
  createPokemon(43, 'Burmy', ['Bug']),
  createPokemon(44, 'Wormadam', ['Bug', 'Grass']),
  createPokemon(45, 'Mothim', ['Bug', 'Flying']),
  createPokemon(46, 'Geodude', ['Rock', 'Ground']),
  createPokemon(47, 'Graveler', ['Rock', 'Ground']),
  createPokemon(48, 'Golem', ['Rock', 'Ground']),
  createPokemon(49, 'Stantler', ['Normal']),
  createPokemon(50, 'Wyrdeer', ['Normal', 'Psychic']),
  createPokemon(51, 'Munchlax', ['Normal']),
  createPokemon(52, 'Snorlax', ['Normal']),
  createPokemon(53, 'Paras', ['Bug', 'Grass']),
  createPokemon(54, 'Parasect', ['Bug', 'Grass']),
  createPokemon(55, 'Pichu', ['Electric']),
  createPokemon(56, 'Pikachu', ['Electric']),
  createPokemon(57, 'Raichu', ['Electric']),
  createPokemon(58, 'Abra', ['Psychic']),
  createPokemon(59, 'Kadabra', ['Psychic']),
  createPokemon(60, 'Alakazam', ['Psychic']),
  createPokemon(61, 'Chimchar', ['Fire']),
  createPokemon(62, 'Monferno', ['Fire', 'Fighting']),
  createPokemon(63, 'Infernape', ['Fire', 'Fighting']),
  createPokemon(64, 'Buneary', ['Normal']),
  createPokemon(65, 'Lopunny', ['Normal']),
  createPokemon(66, 'Cherubi', ['Grass']),
  createPokemon(67, 'Cherrim', ['Grass']),
  createPokemon(68, 'Psyduck', ['Water']),
  createPokemon(69, 'Golduck', ['Water']),
  createPokemon(70, 'Combee', ['Bug', 'Flying']),
  createPokemon(71, 'Vespiquen', ['Bug', 'Flying']),
  createPokemon(72, 'Scyther', ['Bug', 'Flying']),
  createPokemon(73, 'Kleavor', ['Bug', 'Rock']),
  createPokemon(74, 'Scizor', ['Bug', 'Steel']),
  createPokemon(75, 'Heracross', ['Bug', 'Fighting']),
  createPokemon(76, 'Mime Jr.', ['Psychic', 'Fairy']),
  createPokemon(77, 'Mr. Mime', ['Psychic', 'Fairy']),
  createPokemon(78, 'Aipom', ['Normal']),
  createPokemon(79, 'Ambipom', ['Normal']),
  createPokemon(80, 'Magikarp', ['Water']),
  createPokemon(81, 'Gyarados', ['Water', 'Flying']),
  createPokemon(82, 'Shellos', ['Water']),
  createPokemon(83, 'Gastrodon', ['Water', 'Ground']),
  createPokemon(84, 'Qwilfish', ['Dark', 'Poison'], true),
  createPokemon(85, 'Overqwil', ['Dark', 'Poison']),
  createPokemon(86, 'Happiny', ['Normal']),
  createPokemon(87, 'Chansey', ['Normal']),
  createPokemon(88, 'Blissey', ['Normal']),
  createPokemon(89, 'Budew', ['Grass', 'Poison']),
  createPokemon(90, 'Roselia', ['Grass', 'Poison']),
  createPokemon(91, 'Roserade', ['Grass', 'Poison']),
  createPokemon(92, 'Carnivine', ['Grass']),
  createPokemon(93, 'Petilil', ['Grass']),
  createPokemon(94, 'Lilligant', ['Grass', 'Fighting'], true),
  createPokemon(95, 'Tangela', ['Grass']),
  createPokemon(96, 'Tangrowth', ['Grass']),
  createPokemon(97, 'Barboach', ['Water', 'Ground']),
  createPokemon(98, 'Whiscash', ['Water', 'Ground']),
  createPokemon(99, 'Croagunk', ['Poison', 'Fighting']),
  createPokemon(100, 'Toxicroak', ['Poison', 'Fighting']),
  createPokemon(101, 'Ralts', ['Psychic', 'Fairy']),
  createPokemon(102, 'Kirlia', ['Psychic', 'Fairy']),
  createPokemon(103, 'Gardevoir', ['Psychic', 'Fairy']),
  createPokemon(104, 'Gallade', ['Psychic', 'Fighting']),
  createPokemon(105, 'Yanma', ['Bug', 'Flying']),
  createPokemon(106, 'Yanmega', ['Bug', 'Flying']),
  createPokemon(107, 'Hippopotas', ['Ground']),
  createPokemon(108, 'Hippowdon', ['Ground']),
  createPokemon(109, 'Pachirisu', ['Electric']),
  createPokemon(110, 'Stunky', ['Poison', 'Dark']),
  createPokemon(111, 'Skuntank', ['Poison', 'Dark']),
  createPokemon(112, 'Teddiursa', ['Normal']),
  createPokemon(113, 'Ursaring', ['Normal']),
  createPokemon(114, 'Ursaluna', ['Ground', 'Normal']),
  createPokemon(115, 'Goomy', ['Dragon']),
  createPokemon(116, 'Sliggoo', ['Steel', 'Dragon'], true),
  createPokemon(117, 'Goodra', ['Steel', 'Dragon'], true),
  createPokemon(118, 'Onix', ['Rock', 'Ground']),
  createPokemon(119, 'Steelix', ['Steel', 'Ground']),
  createPokemon(120, 'Rhyhorn', ['Rock', 'Ground']),
  createPokemon(121, 'Rhydon', ['Rock', 'Ground']),
  createPokemon(122, 'Rhyperior', ['Rock', 'Ground']),
  createPokemon(123, 'Bonsly', ['Rock']),
  createPokemon(124, 'Sudowoodo', ['Rock']),
  createPokemon(125, 'Lickitung', ['Normal']),
  createPokemon(126, 'Lickilicky', ['Normal']),
  createPokemon(127, 'Togepi', ['Fairy']),
  createPokemon(128, 'Togetic', ['Fairy', 'Flying']),
  createPokemon(129, 'Togekiss', ['Fairy', 'Flying']),
  createPokemon(130, 'Turtwig', ['Grass']),
  createPokemon(131, 'Grotle', ['Grass']),
  createPokemon(132, 'Torterra', ['Grass', 'Ground']),
  createPokemon(133, 'Piplup', ['Water']),
  createPokemon(134, 'Prinplup', ['Water']),
  createPokemon(135, 'Empoleon', ['Water', 'Steel']),
  createPokemon(136, 'Vulpix', ['Fire']),
  createPokemon(137, 'Ninetales', ['Fire']),
  createPokemon(138, 'Growlithe', ['Fire', 'Rock'], true),
  createPokemon(139, 'Arcanine', ['Fire', 'Rock'], true),
  createPokemon(140, 'Tentacool', ['Water', 'Poison']),
  createPokemon(141, 'Tentacruel', ['Water', 'Poison']),
  createPokemon(142, 'Finneon', ['Water']),
  createPokemon(143, 'Lumineon', ['Water']),
  createPokemon(144, 'Magby', ['Fire']),
  createPokemon(145, 'Magmar', ['Fire']),
  createPokemon(146, 'Magmortar', ['Fire']),
  createPokemon(147, 'Magnemite', ['Electric', 'Steel']),
  createPokemon(148, 'Magneton', ['Electric', 'Steel']),
  createPokemon(149, 'Magnezone', ['Electric', 'Steel']),
  createPokemon(150, 'Bronzor', ['Steel', 'Psychic']),
  createPokemon(151, 'Bronzong', ['Steel', 'Psychic']),
  createPokemon(152, 'Elekid', ['Electric']),
  createPokemon(153, 'Electabuzz', ['Electric']),
  createPokemon(154, 'Electivire', ['Electric']),
  createPokemon(155, 'Gligar', ['Ground', 'Flying']),
  createPokemon(156, 'Gliscor', ['Ground', 'Flying']),
  createPokemon(157, 'Gible', ['Dragon', 'Ground']),
  createPokemon(158, 'Gabite', ['Dragon', 'Ground']),
  createPokemon(159, 'Garchomp', ['Dragon', 'Ground']),
  createPokemon(160, 'Nosepass', ['Rock']),
  createPokemon(161, 'Probopass', ['Rock', 'Steel']),
  createPokemon(162, 'Voltorb', ['Electric', 'Grass'], true),
  createPokemon(163, 'Electrode', ['Electric', 'Grass'], true),
  createPokemon(164, 'Rotom', ['Electric', 'Ghost']),
  createPokemon(165, 'Chingling', ['Psychic']),
  createPokemon(166, 'Chimecho', ['Psychic']),
  createPokemon(167, 'Misdreavus', ['Ghost']),
  createPokemon(168, 'Mismagius', ['Ghost']),
  createPokemon(169, 'Cleffa', ['Fairy']),
  createPokemon(170, 'Clefairy', ['Fairy']),
  createPokemon(171, 'Clefable', ['Fairy']),
  createPokemon(172, 'Sneasel', ['Fighting', 'Poison'], true),
  createPokemon(173, 'Sneasler', ['Fighting', 'Poison']),
  createPokemon(174, 'Weavile', ['Dark', 'Ice']),
  createPokemon(175, 'Murkrow', ['Dark', 'Flying']),
  createPokemon(176, 'Honchkrow', ['Dark', 'Flying']),
  createPokemon(177, 'Gastly', ['Ghost', 'Poison']),
  createPokemon(178, 'Haunter', ['Ghost', 'Poison']),
  createPokemon(179, 'Gengar', ['Ghost', 'Poison']),
  createPokemon(180, 'Unown', ['Psychic']),
  createPokemon(181, 'Spheal', ['Ice', 'Water']),
  createPokemon(182, 'Sealeo', ['Ice', 'Water']),
  createPokemon(183, 'Walrein', ['Ice', 'Water']),
  createPokemon(184, 'Remoraid', ['Water']),
  createPokemon(185, 'Octillery', ['Water']),
  createPokemon(186, 'Skorupi', ['Poison', 'Bug']),
  createPokemon(187, 'Drapion', ['Poison', 'Dark']),
  createPokemon(188, 'Mantyke', ['Water', 'Flying']),
  createPokemon(189, 'Mantine', ['Water', 'Flying']),
  createPokemon(190, 'Basculin', ['Water']),
  createPokemon(191, 'Basculegion', ['Water', 'Ghost']),
  createPokemon(192, 'Snorunt', ['Ice']),
  createPokemon(193, 'Glalie', ['Ice']),
  createPokemon(194, 'Froslass', ['Ice', 'Ghost']),
  createPokemon(195, 'Swinub', ['Ice', 'Ground']),
  createPokemon(196, 'Piloswine', ['Ice', 'Ground']),
  createPokemon(197, 'Mamoswine', ['Ice', 'Ground']),
  createPokemon(198, 'Bergmite', ['Ice']),
  createPokemon(199, 'Avalugg', ['Ice', 'Rock'], true),
  createPokemon(200, 'Snover', ['Grass', 'Ice']),
  createPokemon(201, 'Abomasnow', ['Grass', 'Ice']),
  createPokemon(202, 'Zorua', ['Normal', 'Ghost'], true),
  createPokemon(203, 'Zoroark', ['Normal', 'Ghost'], true),
  createPokemon(204, 'Rufflet', ['Normal', 'Flying']),
  createPokemon(205, 'Braviary', ['Psychic', 'Flying'], true),
  createPokemon(206, 'Riolu', ['Fighting']),
  createPokemon(207, 'Lucario', ['Fighting', 'Steel']),
  createPokemon(208, 'Uxie', ['Psychic']),
  createPokemon(209, 'Mesprit', ['Psychic']),
  createPokemon(210, 'Azelf', ['Psychic']),
  createPokemon(211, 'Heatran', ['Fire', 'Steel']),
  createPokemon(212, 'Regigigas', ['Normal']),
  createPokemon(213, 'Cresselia', ['Psychic']),
  createPokemon(214, 'Tornadus', ['Flying']),
  createPokemon(215, 'Thundurus', ['Electric', 'Flying']),
  createPokemon(216, 'Landorus', ['Ground', 'Flying']),
  createPokemon(217, 'Enamorus', ['Fairy', 'Flying']),
  createPokemon(218, 'Dialga', ['Steel', 'Dragon']),
  createPokemon(219, 'Palkia', ['Water', 'Dragon']),
  createPokemon(220, 'Giratina', ['Ghost', 'Dragon']),
  createPokemon(221, 'Arceus', ['Normal']),
  createPokemon(222, 'Phione', ['Water']),
  createPokemon(223, 'Manaphy', ['Water']),
  createPokemon(224, 'Shaymin', ['Grass']),
  createPokemon(225, 'Darkrai', ['Dark']),
];
