
import type { Pokemon } from '@/types/pokemon';

const createPokemon = (id: number, name: string, types: string[], isHisuian: boolean = false): Pokemon => {
  const imageName = name.toLowerCase().replace(' ', '-').replace("'", "").replace(".", "");
  const imageUrl = `https://img.pokemondb.net/sprites/legends-arceus/normal/${imageName}${isHisuian ? '-hisuian' : ''}.png`;
  
  // Special cases for forms
  if (name === 'Wormadam') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/wormadam-plant.png`,
      types
    };
  }
  if (name === 'Basculin') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/basculin-white-striped.png`,
      types
    };
  }
  if (name === 'Tornadus' || name === 'Thundurus' || name === 'Landorus' || name === 'Enamorus') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/${imageName}-incarnate.png`,
      types
    };
  }
  if (name === 'Dialga' || name === 'Palkia') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/${imageName}-origin.png`,
      types
    };
  }
  if (name === 'Shaymin') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/shaymin-land.png`,
      types
    };
  }
  if (name === 'Giratina') {
    return {
      id,
      name,
      imageUrl: `https://img.pokemondb.net/sprites/legends-arceus/normal/giratina-origin.png`,
      types
    };
  }

  return {
    id,
    name,
    imageUrl,
    types,
  };
};

export const pokemonList: Pokemon[] = [
    createPokemon(1, 'Rowlet', ['Grass', 'Flying']),
    createPokemon(2, 'Dartrix', ['Grass', 'Flying']),
    createPokemon(3, 'Decidueye', ['Grass', 'Fighting'], true),
    createPokemon(4, 'Cyndaquil', ['Fire']),
    createPokemon(5, 'Quilava', ['Fire']),
    createPokemon(6, 'Typhlosion', ['Fire', 'Ghost'], true),
    createPokemon(7, 'Oshawott', ['Water']),
    createPokemon(8, 'Dewott', ['Water']),
    createPokemon(9, 'Samurott', ['Water', 'Dark'], true),
    createPokemon(10, 'Bidoof', ['Normal']),
    createPokemon(11, 'Bibarel', ['Normal', 'Water']),
    createPokemon(12, 'Starly', ['Normal', 'Flying']),
    createPokemon(13, 'Staravia', ['Normal', 'Flying']),
    createPokemon(14, 'Staraptor', ['Normal', 'Flying']),
    createPokemon(15, 'Shinx', ['Electric']),
    createPokemon(16, 'Luxio', ['Electric']),
    createPokemon(17, 'Luxray', ['Electric']),
    createPokemon(18, 'Wurmple', ['Bug']),
    createPokemon(19, 'Silcoon', ['Bug']),
    createPokemon(20, 'Beautifly', ['Bug', 'Flying']),
    createPokemon(21, 'Cascoon', ['Bug']),
    createPokemon(22, 'Dustox', ['Bug', 'Poison']),
    createPokemon(23, 'Ponyta', ['Fire']),
    createPokemon(24, 'Rapidash', ['Fire']),
    createPokemon(25, 'Eevee', ['Normal']),
    createPokemon(26, 'Vaporeon', ['Water']),
    createPokemon(27, 'Jolteon', ['Electric']),
    createPokemon(28, 'Flareon', ['Fire']),
    createPokemon(29, 'Espeon', ['Psychic']),
    createPokemon(30, 'Umbreon', ['Dark']),
    createPokemon(31, 'Leafeon', ['Grass']),
    createPokemon(32, 'Glaceon', ['Ice']),
    createPokemon(33, 'Sylveon', ['Fairy']),
    createPokemon(34, 'Zubat', ['Poison', 'Flying']),
    createPokemon(35, 'Golbat', ['Poison', 'Flying']),
    createPokemon(36, 'Crobat', ['Poison', 'Flying']),
    createPokemon(37, 'Drifloon', ['Ghost', 'Flying']),
    createPokemon(38, 'Drifblim', ['Ghost', 'Flying']),
    createPokemon(39, 'Kricketot', ['Bug']),
    createPokemon(40, 'Kricketune', ['Bug']),
    createPokemon(41, 'Buizel', ['Water']),
    createPokemon(42, 'Floatzel', ['Water']),
    createPokemon(43, 'Burmy', ['Bug']),
    createPokemon(44, 'Wormadam', ['Bug', 'Grass']),
    createPokemon(45, 'Mothim', ['Bug', 'Flying']),
    createPokemon(46, 'Geodude', ['Rock', 'Ground']),
    createPokemon(47, 'Graveler', ['Rock', 'Ground']),
    createPokemon(48, 'Golem', ['Rock', 'Ground']),
    createPokemon(49, 'Stantler', ['Normal']),
    createPokemon(50, 'Wyrdeer', ['Normal', 'Psychic']),
    createPokemon(51, 'Munchlax', ['Normal']),
    createPokemon(52, 'Snorlax', ['Normal']),
    createPokemon(53, 'Paras', ['Bug', 'Grass']),
    createPokemon(54, 'Parasect', ['Bug', 'Grass']),
    createPokemon(55, 'Pichu', ['Electric']),
    createPokemon(56, 'Pikachu', ['Electric']),
    createPokemon(57, 'Raichu', ['Electric']),
    createPokemon(58, 'Abra', ['Psychic']),
    createPokemon(59, 'Kadabra', ['Psychic']),
    createPokemon(60, 'Alakazam', ['Psychic']),
    createPokemon(61, 'Chimchar', ['Fire']),
    createPokemon(62, 'Monferno', ['Fire', 'Fighting']),
    createPokemon(63, 'Infernape', ['Fire', 'Fighting']),
    createPokemon(64, 'Buneary', ['Normal']),
    createPokemon(65, 'Lopunny', ['Normal']),
    createPokemon(66, 'Cherubi', ['Grass']),
    createPokemon(67, 'Cherrim', ['Grass']),
    createPokemon(68, 'Psyduck', ['Water']),
    createPokemon(69, 'Golduck', ['Water']),
    createPokemon(70, 'Combee', ['Bug', 'Flying']),
    createPokemon(71, 'Vespiquen', ['Bug', 'Flying']),
    createPokemon(72, 'Scyther', ['Bug', 'Flying']),
    createPokemon(73, 'Kleavor', ['Bug', 'Rock']),
    createPokemon(74, 'Scizor', ['Bug', 'Steel']),
    createPokemon(75, 'Heracross', ['Bug', 'Fighting']),
    createPokemon(76, 'Mime Jr.', ['Psychic', 'Fairy']),
    createPokemon(77, 'Mr. Mime', ['Psychic', 'Fairy']),
    createPokemon(78, 'Aipom', ['Normal']),
    createPokemon(79, 'Ambipom', ['Normal']),
    createPokemon(80, 'Magikarp', ['Water']),
    createPokemon(81, 'Gyarados', ['Water', 'Flying']),
    createPokemon(82, 'Shellos', ['Water']),
    createPokemon(83, 'Gastrodon', ['Water', 'Ground']),
    createPokemon(84, 'Qwilfish', ['Dark', 'Poison'], true),
    createPokemon(85, 'Overqwil', ['Dark', 'Poison']),
    createPokemon(86, 'Happiny', ['Normal']),
    createPokemon(87, 'Chansey', ['Normal']),
    createPokemon(88, 'Blissey', ['Normal']),
    createPokemon(89, 'Budew', ['Grass', 'Poison']),
    createPokemon(90, 'Roselia', ['Grass', 'Poison']),
    createPokemon(91, 'Roserade', ['Grass', 'Poison']),
    createPokemon(92, 'Carnivine', ['Grass']),
    createPokemon(93, 'Petilil', ['Grass']),
    createPokemon(94, 'Lilligant', ['Grass', 'Fighting'], true),
    createPokemon(95, 'Tangela', ['Grass']),
    createPokemon(96, 'Tangrowth', ['Grass']),
    createPokemon(97, 'Barboach', ['Water', 'Ground']),
    createPokemon(98, 'Whiscash', ['Water', 'Ground']),
    createPokemon(99, 'Croagunk', ['Poison', 'Fighting']),
    createPokemon(100, 'Toxicroak', ['Poison', 'Fighting']),
    createPokemon(101, 'Ralts', ['Psychic', 'Fairy']),
    createPokemon(102, 'Kirlia', ['Psychic', 'Fairy']),
    createPokemon(103, 'Gardevoir', ['Psychic', 'Fairy']),
    createPokemon(104, 'Gallade', ['Psychic', 'Fighting']),
    createPokemon(105, 'Yanma', ['Bug', 'Flying']),
    createPokemon(106, 'Yanmega', ['Bug', 'Flying']),
    createPokemon(107, 'Hippopotas', ['Ground']),
    createPokemon(108, 'Hippowdon', ['Ground']),
    createPokemon(109, 'Pachirisu', ['Electric']),
    createPokemon(110, 'Stunky', ['Poison', 'Dark']),
    createPokemon(111, 'Skuntank', ['Poison', 'Dark']),
    createPokemon(112, 'Teddiursa', ['Normal']),
    createPokemon(113, 'Ursaring', ['Normal']),
    createPokemon(114, 'Ursaluna', ['Ground', 'Normal']),
    createPokemon(115, 'Goomy', ['Dragon']),
    createPokemon(116, 'Sliggoo', ['Steel', 'Dragon'], true),
    createPokemon(117, 'Goodra', ['Steel', 'Dragon'], true),
    createPokemon(118, 'Onix', ['Rock', 'Ground']),
    createPokemon(119, 'Steelix', ['Steel', 'Ground']),
    createPokemon(120, 'Rhyhorn', ['Ground', 'Rock']),
    createPokemon(121, 'Rhydon', ['Ground', 'Rock']),
    createPokemon(122, 'Rhyperior', ['Ground', 'Rock']),
    createPokemon(123, 'Bonsly', ['Rock']),
    createPokemon(124, 'Sudowoodo', ['Rock']),
    createPokemon(125, 'Lickitung', ['Normal']),
    createPokemon(126, 'Lickilicky', ['Normal']),
    createPokemon(127, 'Togepi', ['Fairy']),
    createPokemon(128, 'Togetic', ['Fairy', 'Flying']),
    createPokemon(129, 'Togekiss', ['Fairy', 'Flying']),
    createPokemon(130, 'Turtwig', ['Grass']),
    createPokemon(131, 'Grotle', ['Grass']),
    createPokemon(132, 'Torterra', ['Grass', 'Ground']),
    createPokemon(133, 'Porygon', ['Normal']),
    createPokemon(134, 'Porygon2', ['Normal']),
    createPokemon(135, 'Porygon-Z', ['Normal']),
    createPokemon(136, 'Gastly', ['Ghost', 'Poison']),
    createPokemon(137, 'Haunter', ['Ghost', 'Poison']),
    createPokemon(138, 'Gengar', ['Ghost', 'Poison']),
    createPokemon(139, 'Spiritomb', ['Ghost', 'Dark']),
    createPokemon(140, 'Murkrow', ['Dark', 'Flying']),
    createPokemon(141, 'Honchkrow', ['Dark', 'Flying']),
    createPokemon(142, 'Unown', ['Psychic']),
    createPokemon(143, 'Spheal', ['Ice', 'Water']),
    createPokemon(144, 'Sealeo', ['Ice', 'Water']),
    createPokemon(145, 'Walrein', ['Ice', 'Water']),
    createPokemon(146, 'Remoraid', ['Water']),
    createPokemon(147, 'Octillery', ['Water']),
    createPokemon(148, 'Skorupi', ['Poison', 'Bug']),
    createPokemon(149, 'Drapion', ['Poison', 'Dark']),
    createPokemon(150, 'Growlithe', ['Fire', 'Rock'], true),
    createPokemon(151, 'Arcanine', ['Fire', 'Rock'], true),
    createPokemon(152, 'Glameow', ['Normal']),
    createPokemon(153, 'Purugly', ['Normal']),
    createPokemon(154, 'Machop', ['Fighting']),
    createPokemon(155, 'Machoke', ['Fighting']),
    createPokemon(156, 'Machamp', ['Fighting']),
    createPokemon(157, 'Chatot', ['Normal', 'Flying']),
    createPokemon(158, 'Duskull', ['Ghost']),
    createPokemon(159, 'Dusclops', ['Ghost']),
    createPokemon(160, 'Dusknoir', ['Ghost']),
    createPokemon(161, 'Piplup', ['Water']),
    createPokemon(162, 'Prinplup', ['Water']),
    createPokemon(163, 'Empoleon', ['Water', 'Steel']),
    createPokemon(164, 'Mantyke', ['Water', 'Flying']),
    createPokemon(165, 'Mantine', ['Water', 'Flying']),
    createPokemon(166, 'Basculin', ['Water']),
    createPokemon(167, 'Basculegion', ['Water', 'Ghost']),
    createPokemon(168, 'Vulpix', ['Fire']),
    createPokemon(169, 'Ninetales', ['Fire']),
    createPokemon(170, 'Tentacool', ['Water', 'Poison']),
    createPokemon(171, 'Tentacruel', ['Water', 'Poison']),
    createPokemon(172, 'Finneon', ['Water']),
    createPokemon(173, 'Lumineon', ['Water']),
    createPokemon(174, 'Magby', ['Fire']),
    createPokemon(175, 'Magmar', ['Fire']),
    createPokemon(176, 'Magmortar', ['Fire']),
    createPokemon(177, 'Magnemite', ['Electric', 'Steel']),
    createPokemon(178, 'Magneton', ['Electric', 'Steel']),
    createPokemon(179, 'Magnezone', ['Electric', 'Steel']),
    createPokemon(180, 'Bronzor', ['Steel', 'Psychic']),
    createPokemon(181, 'Bronzong', ['Steel', 'Psychic']),
    createPokemon(182, 'Elekid', ['Electric']),
    createPokemon(183, 'Electabuzz', ['Electric']),
    createPokemon(184, 'Electivire', ['Electric']),
    createPokemon(185, 'Gligar', ['Ground', 'Flying']),
    createPokemon(186, 'Gliscor', ['Ground', 'Flying']),
    createPokemon(187, 'Gible', ['Dragon', 'Ground']),
    createPokemon(188, 'Gabite', ['Dragon', 'Ground']),
    createPokemon(189, 'Garchomp', ['Dragon', 'Ground']),
    createPokemon(190, 'Nosepass', ['Rock']),
    createPokemon(191, 'Probopass', ['Rock', 'Steel']),
    createPokemon(192, 'Voltorb', ['Electric', 'Grass'], true),
    createPokemon(193, 'Electrode', ['Electric', 'Grass'], true),
    createPokemon(194, 'Rotom', ['Electric', 'Ghost']),
    createPokemon(195, 'Chingling', ['Psychic']),
    createPokemon(196, 'Chimecho', ['Psychic']),
    createPokemon(197, 'Misdreavus', ['Ghost']),
    createPokemon(198, 'Mismagius', ['Ghost']),
    createPokemon(199, 'Cleffa', ['Fairy']),
    createPokemon(200, 'Clefairy', ['Fairy']),
    createPokemon(201, 'Clefable', ['Fairy']),
    createPokemon(202, 'Sneasel', ['Fighting', 'Poison'], true),
    createPokemon(203, 'Sneasler', ['Fighting', 'Poison']),
    createPokemon(204, 'Weavile', ['Dark', 'Ice']),
    createPokemon(205, 'Snorunt', ['Ice']),
    createPokemon(206, 'Glalie', ['Ice']),
    createPokemon(207, 'Froslass', ['Ice', 'Ghost']),
    createPokemon(208, 'Cranidos', ['Rock']),
    createPokemon(209, 'Rampardos', ['Rock']),
    createPokemon(210, 'Shieldon', ['Rock', 'Steel']),
    createPokemon(211, 'Bastiodon', ['Rock', 'Steel']),
    createPokemon(212, 'Swinub', ['Ice', 'Ground']),
    createPokemon(213, 'Piloswine', ['Ice', 'Ground']),
    createPokemon(214, 'Mamoswine', ['Ice', 'Ground']),
    createPokemon(215, 'Bergmite', ['Ice']),
    createPokemon(216, 'Avalugg', ['Ice', 'Rock'], true),
    createPokemon(217, 'Snover', ['Grass', 'Ice']),
    createPokemon(218, 'Abomasnow', ['Grass', 'Ice']),
    createPokemon(219, 'Zorua', ['Normal', 'Ghost'], true),
    createPokemon(220, 'Zoroark', ['Normal', 'Ghost'], true),
    createPokemon(221, 'Rufflet', ['Normal', 'Flying']),
    createPokemon(222, 'Braviary', ['Psychic', 'Flying'], true),
    createPokemon(223, 'Riolu', ['Fighting']),
    createPokemon(224, 'Lucario', ['Fighting', 'Steel']),
    createPokemon(225, 'Uxie', ['Psychic']),
    createPokemon(226, 'Mesprit', ['Psychic']),
    createPokemon(227, 'Azelf', ['Psychic']),
    createPokemon(228, 'Heatran', ['Fire', 'Steel']),
    createPokemon(229, 'Regigigas', ['Normal']),
    createPokemon(230, 'Cresselia', ['Psychic']),
    createPokemon(231, 'Tornadus', ['Flying']),
    createPokemon(232, 'Thundurus', ['Electric', 'Flying']),
    createPokemon(233, 'Landorus', ['Ground', 'Flying']),
    createPokemon(234, 'Enamorus', ['Fairy', 'Flying']),
    createPokemon(235, 'Dialga', ['Steel', 'Dragon']),
    createPokemon(236, 'Palkia', ['Water', 'Dragon']),
    createPokemon(237, 'Giratina', ['Ghost', 'Dragon']),
    createPokemon(238, 'Arceus', ['Normal']),
    createPokemon(239, 'Phione', ['Water']),
    createPokemon(240, 'Manaphy', ['Water']),
    createPokemon(241, 'Shaymin', ['Grass']),
    createPokemon(242, 'Darkrai', ['Dark']),
];

    